### ISSUE TITLE
I want to translate your README.md into Korean.

### ISSUE THREAD

**Issue by TS-Logic** [catidiana/pacman#1]
I am a Korean computer engineering student. For this semester project I would like to translate your README.md. If you specify Collaborator, we will send a pull request after translation.

**Comment by mampir** [comment]
Sure, that would cool. How did you found about this repository?

**Comment by TS-Logic** [comment]
Experiencing the first contributions is the purpose of our team's project this semester. Our teammates love games .So teammate found your repository while searching in GitHub. We will be contributing by translating your REAMME.md in the future. If possible, we plan to add comments to your cpp file. I have a question. Who is mampir? Are you the same person as cantidiana? It is confusing to whom to ask for a pull request.

**Comment by catidiana** [comment]
Hi Tae.
I do not see any practical use in the translating ReadMe into other languages. English is a language of international communication. I'm from Ukraine myself, Mampir is from Bulgaria, and we stick with English in all our projects.
If you want to contribute with some additional features for the game, do some coding - let me know, we will be happy to cooperate with you. Mampir is a great programming teacher who can give you plenty of help and advice.
Also you can use the current code for your needs. We follow GNU General Public License v3.0.

**Comment by TS-Logic** [comment]
Dear catidiana.
This is tae. I am very excited and looking forward to your suggestions. My teammates feel the same way. We will start analyzing the code from now on. I look forward to learning a lot. Thank you for your favor.

**Comment by mampir** [comment]
Hey, are you still up to adding stuff to the game? Some things you can do are:

- Add new levels
- Add death/image animation
- Put all the images (sprites) in a single image file (sprite sheet), as I've already started doing in pacman.png.
- Draw a font image, so you can draw any text you want.
- Add a score board with names.
- Add a level editor.
- Add sounds we aren't restricted by copyright.

If you are interested I have several other game projects, which you could add stuff to: https://bitbucket.org/Maimun/

I could import them to Github if you want.

By chance and a big coincidence (or is it?), I also happen to be in Seoul currently. :)

**Comment by TS-Logic** [comment]
I'm surprised and glad you are in Seoul! I hope you are having a good time.

I've played pacman games on Linux. When I had eaten all the food at Level 1, I expected to move on to the next level. However, an error occurred and terminated abnormally.

Currently, I'm looking for the cause of the error. I would like to register a new issue with this topic.
