### ISSUE TITLE
Resolve error that occurs when you level up.

### ISSUE THREAD

**Issue by TS-Logic** [catidiana/pacman#2]
- Problem
I played games on Linux Ubuntu 16.04 and 18.04. At level 1, if all the food is eaten, a segmentation fault occurs without going to level 2 and the program terminates.

- Goal
The goal is to make the game progress to level 2 when all food is eaten at level 1.

- Steps to solve the problem
1. Study how to use the gdb debugger.
2. Set breakpoints where you think the cause of the error and look at them line by line.

**Comment by simhj316** [comment]
I could work on it.

**Comment by kimms320** [comment]
I could work on it too.

**Comment by mampir** [comment]
Seems like you've managed to resolve the problem. Thank you for your help! :)
